#!/bin/bash

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# (example) ./run.sh test tests/test_makefile.py::test_linting_passes
function run-tests {
    uv run pytest ${@:-"$THIS_DIR/tests/"}
}

# remove all files generated by tests, builds, or operating this codebase
function clean {
    rm -rf dist build coverage.xml test-reports sample/ tests/cookiecutter_test_configs/
    find . \
      -type d \
      \( \
        -name "*cache*" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -exec rm -r {} + || true

    find . \
      -type f \
      -name "*.pyc" \
      -not -path "*env/*" \
      -exec rm {} +
}

# ---------- small-deploy tasks ----------
# Workflow for every use case: test locally from examples/ first, then small deploy.
#   make run-local DIR=examples/my-new-tool     # plain dev server
#   make run-guarded DIR=examples/my-new-tool   # prod-like behind guard
#   make deploy DIR=examples/my-new-tool        # then ship it

# framework-aware run command (reads small.toml; defaults: flask, app.py)
function _app-run-cmd {
    local dir="$1"
    local fw entry
    fw=$(sed -n 's/^framework *= *"\(.*\)"/\1/p' "$dir/small.toml" 2>/dev/null)
    entry=$(sed -n 's/^entry *= *"\(.*\)"/\1/p' "$dir/small.toml" 2>/dev/null)
    entry="${entry:-app.py}"
    case "${fw:-flask}" in
        gradio) echo "GRADIO_SERVER_NAME=127.0.0.1 GRADIO_SERVER_PORT=\$PORT uv run python $entry" ;;
        *) echo "uv run flask --app ${entry%.py} run --port \$PORT" ;;
    esac
}

# run an app plainly on :8000 (fast dev loop)
function run-local {
    local dir="${1:-$THIS_DIR/examples/counter}"
    local cmd
    cmd=$(_app-run-cmd "$dir")
    echo "app on http://127.0.0.1:8000"
    (cd "$dir" && PORT=8000 sh -c "$cmd")
}

# run an app behind guard.py exactly like production: 403 without the proxy header
function run-guarded {
    local dir="${1:-$THIS_DIR/examples/counter}"
    local cmd
    cmd=$(_app-run-cmd "$dir")
    echo "guard on :8080 (secret dev123) -> app on :8090"
    echo "try: curl -s -o /dev/null -w '%{http_code}\n' http://127.0.0.1:8080/   # 403"
    echo "try: curl -s http://127.0.0.1:8080/ -H 'X-Small-Proxy: dev123'         # 200"
    (cd "$dir" && PORT=8080 SMALL_APP_PORT=8090 SMALL_PROXY_SECRET=dev123 \
        uv run python "$THIS_DIR/packages/runtime/guard.py" sh -c "$cmd")
}

# log in to the small control plane (code echoed inline on the test instance)
function login {
    small login
}

# deploy an app dir with the published CLI
function deploy {
    local dir="${1:-$THIS_DIR/examples/counter}"
    (cd "$dir" && small deploy)
}

# grant a person access to an app: ./run.sh share alice@gmail.com [dir] [--edit]
function share {
    local email="$1"; shift
    local dir="${1:-$THIS_DIR/examples/counter}"
    [[ "$dir" == --* ]] && dir="$THIS_DIR/examples/counter" || shift || true
    (cd "$dir" && small share "$email" "$@")
}

# recent container logs: ./run.sh logs [app-name]
function logs {
    small logs "$@"
}

# fast tests only (no network): Python guard proxy, plus both JS suites.
# run.sh sets -e, so the first failing suite stops the run with its own exit code.
function test:unit {
    uv run pytest "$THIS_DIR/tests/unit_tests/"
    (cd "$THIS_DIR/packages/web" && npm run test:unit)
    (cd "$THIS_DIR/packages/control-plane" && npm test)
    node --test "$THIS_DIR/viz-benchmarks/check-synthetic-fixtures.test.mjs"
    node --test "$THIS_DIR/viz-benchmarks/critic-packet-isolation.test.mjs"
    node --test "$THIS_DIR/tests/evals/learn-grade/*.test.mjs"
    node --test "$THIS_DIR/packages/learn-render/motion/*.test.mjs" "$THIS_DIR/packages/learn-render/motion/service/service.test.mjs"
}

# full integration tests: real deploy to Fly through the published CLI (~30s)
function test:integration {
    uv run pytest "$THIS_DIR/tests/integration_tests/"
}

# deploy the control plane worker to Cloudflare (wrangler.jsonc mounts ../web/dist, so build first)
function cp:deploy {
    (cd "$THIS_DIR/packages/web" && npm run build)
    (cd "$THIS_DIR/packages/control-plane" && npx wrangler deploy)
}

# ---------- web dashboard ----------

# Vite dev server with /api proxied to the control plane (SMALL_API from repo .env)
function web:dev {
    (cd "$THIS_DIR/packages/web" && npm run dev)
}

# build the dashboard and ship it — assets ride on the small-cp worker, same origin as /api
function web:deploy {
    cp:deploy
}

# Playwright e2e: bypass login, see the app list, run a job to finished
function web:test {
    (cd "$THIS_DIR/packages/web" && npx playwright test)
}

# live-tail control plane logs
function cp:tail {
    (cd "$THIS_DIR/packages/control-plane" && npx wrangler tail)
}

# publish a new CLI version to npm: bump packages/cli/package.json version first.
# Auth rides an isolated throwaway npmrc built from NPM_TOKEN in .env — never the user npmrc.
function publish:cli {
    local rc="$THIS_DIR/.npmrc-publish"
    grep '^NPM_TOKEN=' "$THIS_DIR/.env" | sed 's|^NPM_TOKEN=|//registry.npmjs.org/:_authToken=|' > "$rc"
    (cd "$THIS_DIR/packages/cli" && npm test && NPM_CONFIG_USERCONFIG="$rc" npm publish)
    local code=$?
    rm -f "$rc"
    return $code
}

# publish the agent skill to npm as small-skill: bump skills/small/package.json first.
# Auth rides an isolated throwaway npmrc built from NPM_TOKEN in .env — never the user npmrc.
function publish:skill {
    (cd "$THIS_DIR" && .venv/Scripts/python.exe -m pytest tests/unit_tests/skills -q) || return 1
    local rc="$THIS_DIR/.npmrc-publish"
    grep '^NPM_TOKEN=' "$THIS_DIR/.env" | sed 's|^NPM_TOKEN=|//registry.npmjs.org/:_authToken=|' > "$rc"
    (cd "$THIS_DIR/skills/small" && NPM_CONFIG_USERCONFIG="$rc" npm publish)
    local code=$?
    rm -f "$rc"
    return $code
}

# mirror skills/small into its own repo for humans + npx provenance
function skill:mirror {
    (cd "$THIS_DIR" && git subtree push --prefix=skills/small https://github.com/yudhisteer/small-skill.git main)
}

# print all functions in this file
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}