// Author-written documentation, checked against the CLI and handlers.
// Provenance and implementation discrepancies: docs/features/rabbit-hole-docs-source-map.md.
const text = value => ({ type: 'text', value });
const code = (label, value) => ({ type: 'code', label, value });
const note = (title, value) => ({ type: 'note', title, value });
const list = items => ({ type: 'list', items });
const table = (headers, rows) => ({ type: 'table', headers, rows });
const section = (id, title, ...blocks) => ({ id, title, blocks });
const terminal = `npm i -g small-deploy\nsmall login --api __ORIGIN__\nsmall deploy`;
const jobConfig = `name = "hello-job"\nentry = "job.py"\ntype = "job"\n\n[inputs]\nname = { type = "text", default = "world" }\n\n[outputs]\nresult = { path = "result.txt", label = "Greeting" }`;
export const DOCS = {
  introduction: {
    group: 'Get started', title: 'Build with Rabbit Hole.', nav: 'Introduction', description: 'Deploy a Python app, run a job, or connect your own AWS account. Start with the tools you already use.',
    sections: [
      section('start', 'From your terminal to your team.', text('The deployment toolkit uses the small-deploy npm package and the small command. The package and command names are unchanged. You can deploy from an existing project and manage it in the workspace.'), code('Terminal · Node 18+', terminal), text('The login command above selects this preview installation. Use your own installation URL when working elsewhere.')),
      section('choose', 'Choose your way in.', { type: 'links', items: [ ['quickstart', 'Deploy your first app', 'Install, sign in, and ship from your project directory.'], ['api', 'Work with the API', 'Authentication, workspaces, apps, runs and outputs.'], ['byoc', 'Use your own cloud', 'Understand the hosted AWS preview and private installation.'] ] }),
      section('built', 'One toolkit. Different environments.', text('Hosted deployments support Python web apps and CPU jobs. AWS/BYOC currently supports CPU jobs, with capabilities determined by the installation. The CLI selects the deployment path; the underlying APIs differ.'), note('About these docs', 'This reference describes the current repository implementation. AWS features are a preview or private pilot, not a promise of availability in every workspace.')),
    ],
  },
  quickstart: {
    group: 'Get started', title: 'Deploy from your terminal.', nav: 'Quickstart', description: 'An existing Python project, a work-email sign-in, and three commands to get started.',
    sections: [
      section('install', '1. Install the CLI', text('Use Node.js 18 or newer. The CLI is published as small-deploy and installs the small command.'), code('Terminal', 'npm i -g small-deploy\nsmall help')),
      section('signin', '2. Sign in', text('Hosted sign-in sends a six-digit code to your work email. Choose the installation explicitly when using a preview or a company-hosted environment.'), code('This preview installation', 'small login --api __ORIGIN__'), note('Selecting an installation', 'Plain small login uses SMALL_API if set, then the saved login origin, then the hosted default. A shell SMALL_API override should point to the same installation. Private AWS sign-in opens Cognito instead of sending a CLI email code.')),
      section('deploy', '3. Ship your project', text('Run deploy from the directory containing your Python app. The CLI reports the detected entry and framework before building. If detection is ambiguous, define the entry in small.toml.'), code('From your project directory', 'small deploy'), text('Flask, FastAPI, Streamlit and Gradio are supported for hosted web apps. A job deployment builds the app; start the job separately with small run. Deployment provisions runtime resources in the selected hosting environment.')),
      section('workspace', 'Choose a workspace', text('List the workspaces you can access, then pass one of the returned slugs. Selecting a workspace in the browser does not select it in your terminal.'), code('Replace the placeholder with a returned slug', 'small workspaces\nsmall deploy --workspace <slug>'), text('The --workspace flag takes precedence over SMALL_WORKSPACE. The CLI checks that the server activated the requested workspace before accessing an app.')),
      section('next', 'Keep going', { type: 'links', items: [['cli', 'Everyday commands', 'Run, inspect, share and schedule.'], ['configuration', 'Configure your app', 'Entry point, inputs, outputs and hosting target.']] }),
    ],
  },
  cli: {
    group: 'CLI', title: 'Everyday commands.', nav: 'Command reference', description: 'The small command handles deployment and day-to-day operations. Options and capabilities depend on the hosting target.',
    sections: [
      section('jobs', 'Run and inspect jobs', code('Terminal', 'small run <app>\nsmall run <app> --<input-name> <value>\nsmall runs <app>\nsmall logs <run-id>\nsmall run <app> --download ./out'), text('Pass declared inputs as flags. Underscores in input names become hyphens in flags. Defaults are applied; missing required flags produce an error. Download retrieves the most recent successful run’s available outputs.')),
      section('logs', 'Read logs', code('Hosted web request logs', 'small logs <app>\nsmall logs <app> --follow\nsmall logs <app> --status 5xx'), text('For hosted web apps, the default log command reads HTTP request logs. --follow polls new entries. For a job’s printed output, use its run ID. AWS app log commands are routed to the customer installation.')),
      section('manage', 'Projects and workspaces', table(['Command', 'What it does'], [['small list', 'List visible apps, visibility and owner.'], ['small workspaces', 'List workspace slugs you can select.'], ['small init', 'Scaffold small.toml; attempt an initial hosted runbook.'], ['small deploy --env .env', 'Deploy using the supplied secrets file.'], ['small skill', 'Install bundled coding-agent instructions into this project.']])),
      section('sharing', 'Sharing and schedules', code('Hosted apps · use real app names', 'small share teammate@example.com --app <app>\nsmall share teammate@example.com --app <app> --edit\nsmall schedule pause <app>\nsmall schedule resume <app>'), text('Sharing requires owner or editor access. Schedules are UTC cron expressions configured for hosted jobs. Sharing changes and schedules are outside the current AWS CPU-job pilot.')),
      section('watch', 'Watch, review and runbooks', code('Hosted apps', 'small watch\nsmall watch <app>\nsmall review <app>\nsmall review <app> --diff\nsmall runbook <app>\nsmall runbook <app> --write'), text('Watch lists observations from the nightly checks. Review reads a saved deploy review; it does not start a new review of local source. Runbook reads the stored runbook, and --write saves it as RUNBOOK.md. These hosted commands are not supported by the AWS CPU-job preview.')),
    ],
  },
  configuration: {
    group: 'CLI', title: 'Give your app a shape.', nav: 'App configuration', description: 'small.toml defines the entry point, hosting target, inputs and outputs. Keep it beside your source.',
    sections: [
      section('job', 'A small CPU job', text('This example declares a text input and a downloadable output. Create job.py to consume the input and write the declared file.'), code('small.toml', jobConfig), code('job.py', 'import os\nfrom pathlib import Path\n\nname = os.environ.get("SMALL_INPUT_NAME", "world")\n(Path(os.environ["SMALL_OUTPUTS"]) / "result.txt").write_text(f"Hello, {name}!\\n")\nprint(f"Created a greeting for {name}")'), code('Deploy, then run', 'small deploy\nsmall run hello-job --name Ada')),
      section('inputs', 'Inputs and outputs', text('Hosted jobs support text, number, bool, select, date and file inputs. Fields can declare required, default, help and type-specific validation. Input names arrive as SMALL_INPUT_<UPPERCASE_NAME> environment variables.'), text('Write output files into the SMALL_OUTPUTS directory supplied by the runner. Declared output paths are relative to that directory. Outputs become available through the run interface and download command. AWS file support and limits depend on the installed capabilities.')),
      section('aws', 'Choose AWS hosting', code('Add to small.toml for an AWS CPU job', '[deploy]\ntarget = "aws"'), text('A connected AWS workspace or private installation must already exist. This setting does not install infrastructure. Use the BYOC guide before deploying.')),
      section('secrets', 'Configuration is not secret storage', text('Do not commit credentials to small.toml. Hosted deployments can read a local .env file and send declared secrets to the runtime. The current AWS CPU-job pilot does not support app secrets or extra runtime roles.'), note('Keep examples small', 'Schedules, persistent volumes and system packages have different support across hosting targets. Do not assume a hosted configuration will work unchanged on AWS.')),
    ],
  },
  api: {
    group: 'API', title: 'The API, directly.', nav: 'Overview & authentication', description: 'The HTTP API used by the CLI and dashboard. Start with authentication and the workspace you intend to access.',
    sections: [
      section('base', 'Base URL', code('API for this preview', '__ORIGIN__/api'), text('Replace the origin when using another installation. Endpoint paths below include /api; do not append that prefix twice. Hosted endpoints in this section are not interchangeable with the AWS job API.')),
      section('auth', 'Authenticate your requests', text('Run small login against the intended installation. Hosted API requests accept the CLI bearer token; the same-origin dashboard uses its session cookie. Keep tokens in your own terminal or secret store, never in browser code or a public repository.'), code('Example · token supplied through your environment', 'curl "__ORIGIN__/api/workspaces" \\\n  -H "Authorization: Bearer $SMALL_TOKEN"'), text('The CLI stores the hosted token in ~/.small/config.json. SMALL_TOKEN can supply it for automation. Private AWS uses Cognito tokens tied to that installation and ignores hosted SMALL_TOKEN credentials.')),
      section('workspace', 'Select the workspace', code('Example · replace the returned workspace slug', 'curl "__ORIGIN__/api/apps" \\\n  -H "Authorization: Bearer $SMALL_TOKEN" \\\n  -H "X-Small-Workspace: <slug>"'), text('GET /api/workspaces returns accessible workspaces and the active slug. The CLI validates selection before app requests. A direct client should verify that the returned active slug matches the requested workspace.')),
      section('endpoints', 'Core hosted endpoints', table(['Method', 'Path', 'Purpose'], [['GET', '/api/workspaces', 'Accessible workspaces and active selection.'], ['GET', '/api/apps', 'Apps visible in the active workspace.'], ['GET', '/api/apps/<app>', 'An app and its input configuration.'], ['POST', '/api/runs', 'Start a deployed hosted job.'], ['GET', '/api/runs?app=<app>', 'Run history for an app.'], ['GET', '/api/runs/<run-id>', 'Run status and printed output.'], ['GET', '/api/request-logs?app=<app>', 'HTTP request logs for a hosted app.'], ['POST', '/api/share', 'Grant app access; requires owner/editor.'], ['POST', '/api/schedule', 'Set or pause a hosted job schedule.'], ['GET', '/api/watch', 'Open Watch observations.']])),
      section('errors', 'Read the response', text('API errors use JSON with an error message. A 401 indicates missing or invalid authentication; a 403 indicates insufficient access. A 404 can mean the app or run is absent from the selected workspace. Check the HTTP status before using the response.'), code('Example error', '{ "error": "run small login first" }'), note('No live requests from these docs', 'Examples are for your terminal. Copying a command does not execute it, create a run, change access or provision infrastructure.')),
    ],
  },
  'api/runs': {
    group: 'API', title: 'Jobs, logs & outputs.', nav: 'Runs & outputs', description: 'Start a hosted job, follow its progress, and retrieve its output. AWS jobs use a separate runtime path.',
    sections: [
      section('start', 'Start a run', code('Example request · replace hello-job with your deployed job', 'curl -X POST "__ORIGIN__/api/runs" \\\n  -H "Authorization: Bearer $SMALL_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"app":"hello-job","inputs":{"name":"Ada"}}\''), text('The response contains runId. Inputs must match the deployed job schema. The app must be a built job that your identity can access.'), code('Example response shape', '{ "runId": "<run-id>" }')),
      section('poll', 'Read status and log lines', code('Example request', 'curl "__ORIGIN__/api/runs/<run-id>?after=-1" \\\n  -H "Authorization: Bearer $SMALL_TOKEN"'), text('The response includes status, exitCode, lines and cursor. Start with after=-1, then use the returned cursor to request subsequent lines. Keep the cursor when a response contains no new output.')),
      section('outputs', 'List and download outputs', table(['Method', 'Path', 'Response'], [['GET', '/api/runs/<run-id>/outputs', 'An outputs list with file metadata.'], ['GET', '/api/runs/<run-id>/outputs/<name>', 'The file contents.']]), text('Use the same authentication and workspace context. Encode file names when constructing URLs. The CLI handles this through small run <app> --download ./out.')),
      section('files', 'Send file inputs', text('Hosted file inputs use multipart/form-data. A body field contains the JSON app and scalar inputs; each file is an input:<name> part. The hosted per-run file cap is 100 MB. This is different from private AWS file limits.'), note('Use the CLI for the simplest path', 'small run accepts local file paths for declared file input flags and performs validation before upload.')),
    ],
  },
  byoc: {
    group: 'AWS / BYOC', title: 'Your cloud. Your workloads.', nav: 'Overview', description: 'Run CPU jobs in your AWS account. The deployment path depends on where your workspace is hosted.',
    sections: [
      section('choose', 'Two ways to use AWS', table(['', 'Hosted AWS preview', 'Private AWS installation'], [['Dashboard', 'Hosted development workspace', 'Your company’s installation URL'], ['Sign-in', 'Hosted work-email authentication', 'Cognito in the browser'], ['Runtime', 'Customer AWS', 'Customer AWS'], ['Job API', 'Customer AWS endpoint discovered by the CLI', 'Installation /api/jobs routes'], ['Available features', 'Connection-specific preview capabilities', 'Capabilities advertised by the installed release']])),
      section('connect', 'Connect from a hosted workspace', text('In the intended workspace, open Settings → Connections → AWS. Supply the account and initial app details, review the installation in that account’s AWS console, then return to Finish connecting. Additional CPU jobs reuse the connection.'), text('The hosted preview supports one connection per workspace in us-east-1. The connection installer can deploy; workspace members can run and inspect supported jobs. Installation creates AWS resources in the customer account.')),
      section('deploy', 'Deploy to the selected connection', code('small.toml', 'name = "hello-job"\nentry = "job.py"\ntype = "job"\n\n[deploy]\ntarget = "aws"'), code('Replace <slug> with a workspace from the list', 'small login --api __ORIGIN__\nsmall workspaces\nsmall deploy --workspace <slug>\nsmall run hello-job --workspace <slug>'), text('Before uploading, the CLI prints the target workspace, account and region. Verify that target. It stops if the connection is missing, incomplete, or requires a capability the installation does not provide.')),
      section('boundary', 'Where the data goes', text('For the hosted AWS preview, source uploads and job data flow directly between the client and customer AWS. The hosted connection service handles connection metadata and scoped access. In a private installation, the dashboard, authentication and job API also live in customer AWS.'), text('Source is uploaded to customer S3; builds use CodeBuild, images use ECR, jobs use Fargate, and logs use CloudWatch. Use the private installation guide when your dashboard itself is hosted in AWS.')),
    ],
  },
  'byoc/private': {
    group: 'AWS / BYOC', title: 'Inside your AWS account.', nav: 'Private installation', description: 'Use the installation URL and workspace supplied by your administrator. Installing the CLI does not install the AWS stack.',
    sections: [
      section('login', 'Sign in with Cognito', code('Command template · replace placeholders', 'npm i -g small-deploy\nsmall login --api <installation-url>\nsmall workspaces'), text('Login opens Cognito in your browser and returns to the CLI through http://127.0.0.1:8766/auth/callback using PKCE. Complete sign-in on the computer running the command and leave it running until login finishes.'), note('Working over SSH', 'Forward local port 8766 to port 8766 on the remote host before signing in. --no-browser prints the link but does not create the forwarding connection.')),
      section('target', 'Configure and deploy', text('Set type = "job" and [deploy] target = "aws" in small.toml. Select a slug returned by small workspaces. A conflicting SMALL_API environment variable must be cleared or set to the same installation.'), code('Command template', 'small deploy --workspace <slug>\nsmall run <app> --workspace <slug> --<input-name> <value>\nsmall logs <app> --workspace <slug>\nsmall run <app> --workspace <slug> --download ./out')),
      section('capabilities', 'Follow the installed capabilities', text('Private releases can support scalar inputs, file inputs, fixed constants, tooltips and exact per-app AWS grants. The CLI discovers these capabilities. Update the installation when a capability is missing; updating the npm package alone does not update AWS infrastructure.'), text('File-capable private releases allow up to five files, 10 MiB each. File types and input names come from your job configuration. Constants are typed, non-secret values supplied through SMALL_CONSTANTS JSON.')),
      section('access', 'Approve app access', text('When declared AWS access changes, deployment waits before uploading source. The owner reviews the exact actions and resources in Settings → Connections → AWS → App access. Unchanged grants reuse approval; cancellations stop deployment.'), { type: 'links', items: [['byoc/permissions', 'Permissions and current limits', 'Grant syntax, approvals and unsupported workloads.']] }),
    ],
  },
  'byoc/permissions': {
    group: 'AWS / BYOC', title: 'Explicit access. Clear limits.', nav: 'Permissions & limits', description: 'Declare only the AWS actions your job uses, against the resources it needs. Capability support varies by installation.',
    sections: [
      section('grants', 'Declare per-app grants', text('Private installations with configurable grants accept exact action/resource pairs. Keep the grants array on one physical line: the CLI uses a limited TOML parser.'), code('Example only · replace the bucket and prefix', '[aws]\ngrants = [{ action = "s3:GetObject", resource = "arn:aws:s3:::<bucket>/<prefix>/*" }]'), text('Use the installation’s advertised actions and region. At most 20 grants are accepted. Wildcard actions, Resource = "*", cross-account resources and IAM/STS administration are unsupported. The administrator’s allowlist is a ceiling; it does not grant access to an app.')),
      section('approval', 'Keep approval tied to the app', text('The owner reviews changes in the existing AWS connection settings. Approval replaces that app’s grant set. A missing endpoint, encrypted resource or unsupported action may require an administrator change; widening permissions is not a substitute for understanding the failure.'), text('The hosted preview retains its narrower per-app S3 access workflow. Do not assume private configurable grants are available on every hosted connection.')),
      section('limits', 'Current CPU-job limits', list(['CPU jobs only: no GPU jobs or long-running web servers.', 'No app secrets, arbitrary extra AWS roles or system packages.', 'No persistent volumes or schedules in this job pilot.', 'Hosted AI review, runbook and Coaching commands do not run through this path.', 'Private file inputs, constants and configurable grants require the corresponding installed capabilities.']), text('Use the account, region and installation URL returned by your own environment. These docs intentionally do not include a customer’s account identifiers or private deployment addresses.')),
    ],
  },
};
export const docsPath = slug => `/docs${slug === 'introduction' ? '' : `/${slug}`}`;
export const DOCS_PATHS = Object.keys(DOCS).map(docsPath);
export function currentDoc(pathname) {
  const slug = pathname.replace(/^\/docs\/?/, '').replace(/\/$/, '') || 'introduction';
  return DOCS[slug] ? slug : null;
}
