// Authored UI fixtures. These are not extracted from the app or generated by a model.
export const sourceSample = `# lesson_geometry.py: illustrative teaching example
# Decoded distances in a common coordinate system, not YOLO's implementation.

def decode_box(point, distances):
    x, y = point
    left, top, right, bottom = distances
    if min(distances) < 0:
        raise ValueError("Distances must be non-negative")
    return (x - left, y - top, x + right, y + bottom)

point = (160, 120)
distances = (60, 40, 100, 70)
box = decode_box(point, distances)
print(box)
`;

export const architecturePages = [
  ['How does an image become detections?', 'Image → Backbone → Neck → Head', 'The backbone extracts features, the neck combines information across scales, and the head predicts class scores and box geometry. The head produces candidate predictions; filtering comes afterward.'],
  ['Backbone: extracting features', 'Pixels → learned features → feature maps', 'Filters learned during training respond to patterns in the image. Successive layers transform these representations. A feature map is a set of numerical responses, not a labelled picture of an object.'],
  ['Why different scales?', 'Fine spatial detail + broader context', 'Fine-resolution maps preserve more spatial detail. Coarser representations incorporate information from larger image regions. Different resolutions provide complementary information for objects of different sizes.'],
  ['Neck: combining information', 'Feature maps → cross-scale fusion → head', 'The neck combines features across resolutions. It does not simply average them, and it does not choose the final labels or boxes. The diagram is a conceptual illustration, not a recording of model activations.'],
  ['Head: predicting what and where', 'Features → class scores + box geometry', 'The split head has separate branches for classification and box prediction. A class score is not measured accuracy. Many locations can propose overlapping boxes for the same object.'],
  ['What does anchor-free mean?', 'Reference point + distances → a box', 'Anchor-free prediction does not depend on predefined anchor-box templates. Spatial reference points still exist. The notebook uses already-decoded distances to illustrate geometry, without recreating the learned YOLO head.'],
  ['Put the pieces together', 'Extract → combine → predict', 'Trace one image through the backbone, neck, and head. You now have candidate predictions. Confidence filtering and non-maximum suppression are the next lesson; they turn those candidates into the reported detections.'],
];

export const architectureLesson = {
  id: 'preview-yolo-architecture', title: 'Inside the YOLOv8 architecture',
  pages: architecturePages.map(([title, visual, narration]) => ({ title, narration,
    blocks: [{ kind: 'text', text: visual }, { kind: 'question', text: 'Which part of this process would you like to explore?' }] })),
};

export const sampleCourse = {
  title: 'From classification to object detection',
  lessons: [
    { id: 'sigmoid-demo', title: 'Logistic regression', pages: [
      { title: 'What is logistic regression?' }, { title: 'The formula' }, { title: 'The sigmoid function' },
    ] },
    architectureLesson,
  ],
};

export const quiz = [
  { question: 'Which component combines features across scales?', options: ['Backbone', 'Neck', 'Detection head'], correct: 1, explanation: 'The neck combines information across resolutions before passing it to the detection head.', page: 3 },
  { question: 'What does anchor-free remove?', options: ['All spatial reference points', 'The need for training data', 'Predefined anchor-box templates'], correct: 2, explanation: 'Spatial reference points remain. Anchor-free refers to the absence of predefined anchor-box templates.', page: 5 },
  { question: 'The head has produced many overlapping boxes. Are these necessarily the final detections?', options: ['Yes, every box is final', 'No, they are candidate predictions'], correct: 1, explanation: 'Filtering and duplicate suppression happen after prediction. The next lesson explains those steps.', page: 6 },
];
export const flashcards = [
  ['What is the backbone’s role?', 'Transform image pixels into learned feature representations.'],
  ['Why combine features across scales?', 'To use complementary spatial detail and broader context.'],
  ['What does the neck do?', 'Combine information across feature resolutions before prediction.'],
  ['What does the split detection head predict?', 'Class scores and box geometry through separate branches.'],
  ['Does anchor-free mean there are no reference points?', 'No. It removes predefined anchor-box templates, not spatial reference points.'],
];
