import materialPlan from '../../../docs/courses/nanogpt/lesson-01-plan.md?raw';
// Narration clips + per-part timings, generated by scripts/generate-lesson-audio.mjs.
import narrationParts from './nanogpt-audio.json';

// Owner-approved two-page rendering fixture, not a generated course or syllabus.
export const nanoSourceVersion = '3adf61e154c3fe3fca428ad6bc3818b27a3b8291';
export const nanoRevision = Number(materialPlan.match(/Plan revision: (\d+)/)[1]);
const sections = materialPlan.split(/^## /m).filter(section => /^Page [1-6] —/.test(section));
export const nanoMaterials = sections.map(section => {
  const parts = Object.fromEntries(section.split(/^### /m).slice(1).map(part => {
    const [heading, ...body] = part.split('\n');
    return [heading.trim(), body.join('\n').trim()];
  }));
  return { title: section.split('\n')[0].trim().replace(/^Page \d+ — /, '').replace(/\s+\([^)]*seconds\)$/, ''),
    narration: parts['Spoken or written explanation'].replace(/^[“”]|[“”]$/g, ''),
    reading: parts['Further explanations'], references: parts['References and further reading'] };
});

const text = (objectId, value, x, y, w = 720, size = 'm', pause = 1400, color) => ({ type: 'text', objectId, text: value, x, y, w, size, pause, ...(color ? { color } : {}) });
const box = (objectId, x, y, w, h, color = 'grey', fill = 'none') => ({ type: 'geo', objectId, x, y, props: { geo: 'rectangle', w, h, color, fill, size: 's', dash: 'solid' } });
const arrow = (objectId, x, y, dx, dy, color = 'violet') => ({ type: 'arrow', objectId, x, y, props: { start: { x: 0, y: 0 }, end: { x: dx, y: dy }, color, size: 's', dash: 'solid', arrowheadEnd: 'arrow' } });
const tiles = (objectId, values, x, y, colors = []) => values.flatMap((value, i) => [
  box(objectId, x + i * 64, y, 52, 54, colors[i] || 'blue'),
  text(objectId, value, x + i * 64 + 14, y + 7, 34, 'm', 250),
]);
const meaning = (kind, label, originalText, relatedObjectIds = []) => ({ kind, label, originalText, relatedObjectIds });

export const nanoLesson = {
  // Leave room for tldraw's existing page menu, bottom tools and style panel.
  id: `course-1001-${nanoRevision}`, title: 'What nanoGPT does', viewport: { x: -30, y: -65, w: 1040, h: 770 },
  pages: [
    {
      // Each part's scene segment is stretched to its clip so drawing tracks speech.
      ...nanoMaterials[0], audioParts: narrationParts[0],
      objects: {
        title: meaning('title', 'The prediction task', 'What does a language model predict?', ['prefix', 'prediction']),
        prefix: meaning('diagram', 'Available text: Hell', 'The teaching example has H, e, l, l and an unknown next character. This is not a measured model prediction.', ['prediction']),
        prediction: meaning('diagram', 'Possible next characters', 'Given Hell, possible next characters include o, a space and other vocabulary characters. No measured probabilities are shown.', ['prefix', 'probabilities']),
        probabilities: meaning('annotation', 'Probabilities, not guarantees', 'A prediction assigns probabilities; it does not guarantee the next character.', ['prediction']),
        check: meaning('question', 'One token, then repeat', 'Do we need to predict the whole sentence at once? No. Predict one token, then repeat.', ['prefix', 'prediction']),
        transition: meaning('annotation', 'Represent text as numbers', 'How can we represent this text as numbers?', []),
      },
      scene: [
        text('title', 'What does a language model predict?', 40, 20, 760, 'l'),
        ...tiles('prefix', ['H', 'e', 'l', 'l', '?'], 45, 125, ['blue', 'blue', 'blue', 'blue', 'yellow']),
        text('prefix', 'Given the text so far,\npredict the next token.', 45, 210, 345, 'm', 2200, 'blue'),
        arrow('prediction', 360, 152, 65, 0), box('prediction', 435, 105, 360, 135, 'violet'),
        text('prediction', 'Possible next:', 455, 118, 320, 'm', 300, 'violet'),
        ...tiles('prediction', ['o', '␣', '?'], 455, 155, ['orange', 'orange', 'orange']),
        text('probabilities', 'Probabilities: not guarantees', 45, 320, 735, 'm', 2000, 'orange'),
        text('check', 'Whole sentence at once? No: one token, then repeat.', 45, 390, 735, 'm', 2600, 'red'),
        text('transition', 'Next: turn text into numbers', 45, 460, 735, 'm', 800, 'green'),
      ],
    },
    {
      ...nanoMaterials[1], audioParts: narrationParts[1],
      objects: {
        title: meaning('title', 'Text → tokens → integer IDs', 'Represent characters with consistent integer IDs, then decode to recover the text.', ['characters', 'vocabulary', 'ids']),
        characters: meaning('diagram', 'Hello character positions', 'Hello has five character positions, including two occurrences of l.', ['vocabulary', 'ids']),
        vocabulary: meaning('diagram', 'Toy character vocabulary', 'Toy mapping: H = 0, e = 1, l = 2, o = 3, space = 4. Actual IDs depend on the dataset vocabulary.', ['characters', 'ids']),
        ids: meaning('diagram', 'Encoded Hello: [0, 1, 2, 2, 3]', 'Encoding Hello with the toy vocabulary gives [0, 1, 2, 2, 3]. Both l characters map to ID 2.', ['characters', 'vocabulary', 'decode']),
        encoding: meaning('diagram', 'Encoding arrows: character → ID', 'Each character position maps to its integer ID using the toy vocabulary.', ['vocabulary', 'ids']),
        decode: meaning('annotation', 'Decode IDs back to text', 'Decode [0, 1, 2, 2, 3] with the same dictionary to recover Hello. IDs are labels, not importance scores or learned embeddings.', ['vocabulary', 'ids']),
        check: meaning('question', 'Try encoding a new string', 'Use the same toy vocabulary to encode lo H, including the space. The exercise is below the canvas.', ['vocabulary']),
      },
      scene: [
        text('title', 'Text → tokens → integer IDs', 40, 20, 760, 'l'),
        ...tiles('characters', ['H', 'e', 'l', 'l', 'o'], 45, 115, ['blue', 'blue', 'orange', 'orange', 'blue']),
        text('vocabulary', 'Toy vocabulary', 430, 100, 350, 'm', 1400, 'blue'),
        ...['H → 0', 'e → 1', 'l → 2', 'o → 3', '[space] → 4'].map((v, i) => text('vocabulary', v, 455, 143 + i * 35, 310, 'm', 500, 'blue')),
        ...Array.from({ length: 5 }, (_, i) => arrow('encoding', 71 + i * 64, 180, 0, 105)),
        ...tiles('ids', ['0', '1', '2', '2', '3'], 45, 300, ['orange', 'orange', 'orange', 'orange', 'orange']),
        text('ids', 'Same character, same ID. Spaces have IDs too.', 45, 385, 740),
        arrow('decode', 390, 335, 0, -190), text('decode', 'decode', 323, 235, 100, 'm', 1200, 'violet'),
        text('vocabulary', 'Toy IDs only. Actual IDs depend on the dataset.', 45, 440, 735),
        text('decode', 'An ID is a label, not an importance score.', 45, 480, 735),
        text('check', 'Your turn below: encode “lo H”.', 45, 535, 750, 'm', 1400, 'red'),
      ],
    },
    {
      ...nanoMaterials[2], audioParts: narrationParts[2],
      objects: {
        title: meaning('title', 'The text grades itself', 'Use the prefix to predict what follows.', ['sequence', 'rows']),
        sequence: meaning('diagram', 'Hello with positions 1–5', 'The sequence Hello with numbered positions 1 to 5. Position 5 has no recorded next character in this example.', ['demo', 'rows', 'positions']),
        positions: meaning('annotation', 'Position numbers', 'Positions 1 to 5 label the characters of Hello; positions 1 to 4 each have an observed next character.', ['sequence']),
        demo: meaning('diagram', 'Worked example: H → e', 'At position 1 the available prefix is H and the observed next character is e. An explicitly unscored worked example.', ['sequence']),
        choose: meaning('question', 'Pick a position below', 'The learner picks a position 1–4 below the canvas and chooses the character that followed that prefix in Hello.', ['sequence']),
        rows: meaning('diagram', 'Input row', 'Input row H e l l: the characters available as prefixes. These are observed training inputs, not model predictions.', ['sequence', 'targets', 'captions']),
        targets: meaning('diagram', 'Shifted target row', 'Each arrow pairs an input position with its observed next character; the orange row e l l o is the same text shifted one position.', ['rows', 'captions']),
        captions: meaning('annotation', 'Context and context window', 'Context = tokens available for this prediction. Context window = the maximum number of input tokens considered at once.', ['rows']),
        transition: meaning('annotation', 'Toward training', 'How can comparing a prediction with its target improve a model?', []),
      },
      scene: [
        text('title', 'Use the prefix to predict what follows', 40, 20, 760, 'l'),
        ...tiles('sequence', ['H', 'e', 'l', 'l', 'o'], 45, 105),
        ...['1', '2', '3', '4', '5'].map((v, i) => text('positions', v, 45 + i * 64 + 18, 165, 30, 'm', 150, 'violet')),
        text('demo', 'H → e  (worked example)', 45, 215, 360, 'm', 1800),
        text('choose', 'Your turn: tap a position tile above, then answer below ↓', 45, 260, 735, 'm', 2400, 'red'),
        text('rows', 'Observed training pairs', 45, 330, 400, 'm', 600),
        ...tiles('rows', ['H', 'e', 'l', 'l'], 45, 365),
        ...Array.from({ length: 4 }, (_, i) => arrow('targets', 71 + i * 64, 424, 32, 64)),
        ...tiles('targets', ['e', 'l', 'l', 'o'], 77, 495, ['orange', 'orange', 'orange', 'orange']),
        box('captions', 45, 563, 730, 84, 'yellow', 'semi'),
        text('captions', '• Context: the tokens this prediction can see.\n• Context window: the most it can see at once.', 65, 575, 690, 'm', 2200),
        text('transition', 'Next: how does comparing help the model learn?', 45, 665, 735, 'm', 800, 'green'),
      ],
    },
    {
      ...nanoMaterials[3], audioParts: narrationParts[3],
      objects: {
        title: meaning('title', 'Same task, different use', 'Training and generation share the same prediction task but do different jobs.', ['training', 'generation']),
        training: meaning('diagram', 'Training lane', 'Training: known text, predict, compare with the observed next token, update parameters. Learned parameters change.', ['trainingSteps', 'generation', 'validation']),
        trainingSteps: meaning('diagram', 'Training steps', 'Known text, predict, compare with the observed target, update the parameters (θ).', ['training', 'generationSteps']),
        generation: meaning('diagram', 'Generation lane', 'Generation: prompt, predict, select a token, append it. Text grows; learned parameters stay fixed.', ['generationSteps', 'training']),
        generationSteps: meaning('diagram', 'Generation steps', 'Prompt, predict, select a token, append it - then predict again with the longer prefix.', ['generation', 'trainingSteps']),
        captions: meaning('annotation', 'What parameters are', 'Learned parameters are adjustable numerical values inside the model.', ['training']),
        validation: meaning('annotation', 'Validation', 'Validation compares predictions with known targets, without updating parameters.', ['training']),
        check: meaning('question', 'Longer answer, new weights?', 'Does a longer generated answer mean the parameters changed? No - the generated text changed; the learned parameters stayed fixed. Answered below the canvas.', ['generation']),
        transition: meaning('annotation', 'Toward the repository', 'Where do training and generation live in nanoGPT?', []),
      },
      scene: [
        text('title', 'Same prediction task, different use', 40, 20, 760, 'l'),
        box('training', 45, 100, 730, 120, 'light-violet'),
        text('training', 'Training', 65, 110, 200, 'm', 300, 'violet'),
        box('trainingSteps', 65, 150, 150, 48, 'blue'), text('trainingSteps', 'known text', 85, 163, 130, 's', 150),
        arrow('trainingSteps', 221, 174, 26, 0),
        box('trainingSteps', 253, 150, 150, 48, 'violet'), text('trainingSteps', 'predict', 293, 163, 100, 's', 150),
        arrow('trainingSteps', 409, 174, 26, 0),
        box('trainingSteps', 441, 150, 150, 48, 'violet'), text('trainingSteps', 'compare', 478, 163, 100, 's', 150),
        arrow('trainingSteps', 597, 174, 26, 0),
        box('trainingSteps', 629, 150, 130, 48, 'orange'), text('trainingSteps', 'update θ', 655, 163, 90, 's', 700),
        box('generation', 45, 250, 730, 120, 'light-violet'),
        text('generation', 'Generation', 65, 260, 200, 'm', 300, 'violet'),
        box('generationSteps', 65, 300, 150, 48, 'blue'), text('generationSteps', 'prompt', 100, 313, 90, 's', 150),
        arrow('generationSteps', 221, 324, 26, 0),
        box('generationSteps', 253, 300, 150, 48, 'violet'), text('generationSteps', 'predict', 293, 313, 100, 's', 150),
        arrow('generationSteps', 409, 324, 26, 0),
        box('generationSteps', 441, 300, 150, 48, 'violet'), text('generationSteps', 'select', 483, 313, 80, 's', 150),
        arrow('generationSteps', 597, 324, 26, 0),
        box('generationSteps', 629, 300, 130, 48, 'orange'), text('generationSteps', 'append', 657, 313, 80, 's', 700),
        box('captions', 45, 390, 730, 84, 'yellow', 'semi'),
        text('captions', 'θ = learned parameters:\nadjustable numbers inside the model', 65, 402, 690, 'm', 1800),
        text('validation', 'Validation: compare only: parameters never change', 45, 495, 735, 'm', 1600),
        text('check', 'Check below the canvas ↓', 45, 545, 400, 'm', 2000, 'red'),
        text('transition', 'Next: where does each live in nanoGPT?', 45, 595, 735, 'm', 800, 'green'),
      ],
    },
    {
      ...nanoMaterials[4], audioParts: narrationParts[4],
      objects: {
        title: meaning('title', 'The pipeline in nanoGPT', 'nanoGPT makes the training and generation pipeline concrete.', ['stages']),
        stages: meaning('diagram', 'Three stages', 'Prepare data, train a model, generate text - the whole workflow in three stages.', ['prepare', 'train', 'generate']),
        prepare: meaning('diagram', 'Prepare data', 'Tiny Shakespeare text goes through prepare.py into train.bin and val.bin. train.bin holds learning examples; val.bin holds held-out evaluation examples.', ['stages', 'train']),
        train: meaning('diagram', 'Train a model', 'train.py uses the prepared examples, guided by config/train_shakespeare_char.py, and saves a model checkpoint.', ['prepare', 'generate']),
        generate: meaning('diagram', 'Generate text', 'sample.py loads the checkpoint and extends a prompt into generated text. model.py supplies the shared GPT implementation.', ['train']),
        closing: meaning('annotation', 'Examples versus learned state', 'Data files are examples. A checkpoint stores learned state. train.bin does not contain the learned weights.', ['prepare', 'train']),
        transition: meaning('annotation', 'Toward the recap', 'Can you trace one string through this entire workflow?', []),
      },
      scene: [
        text('title', 'nanoGPT makes the pipeline concrete', 40, 20, 760, 'l'),
        box('stages', 45, 100, 210, 90, 'violet'), text('stages', 'Prepare data', 60, 128, 190, 'm', 400, 'violet'),
        arrow('stages', 262, 145, 45, 0),
        box('stages', 315, 100, 210, 90, 'violet'), text('stages', 'Train a model', 330, 128, 190, 'm', 400, 'violet'),
        arrow('stages', 532, 145, 45, 0),
        box('stages', 585, 100, 210, 90, 'violet'), text('stages', 'Generate text', 600, 128, 190, 'm', 800, 'violet'),
        arrow('prepare', 150, 195, 0, 25),
        text('prepare', 'Tiny Shakespeare\nprepare.py\ntrain.bin / val.bin', 55, 235, 200, 'm', 2200, 'blue'),
        arrow('train', 420, 195, 0, 25),
        text('train', 'train.py\nconfig settings\n→ checkpoint', 325, 235, 210, 'm', 2200, 'blue'),
        arrow('generate', 690, 195, 0, 25),
        text('generate', 'sample.py\ncheckpoint\n→ generated text', 595, 235, 200, 'm', 2200, 'blue'),
        text('generate', 'model.py: the shared GPT implementation', 45, 410, 735, 'm', 1400, 'violet'),
        box('closing', 45, 450, 730, 84, 'orange', 'semi'),
        text('closing', '• train.bin holds the examples\n• the checkpoint holds the learned state', 65, 462, 690, 'm', 2600, 'orange'),
        text('transition', 'Trace one string through the whole pipeline!', 45, 560, 735, 'm', 800, 'red'),
      ],
    },
    {
      ...nanoMaterials[5], audioParts: narrationParts[5],
      objects: {
        title: meaning('title', 'Check your mental model', 'Text in, next-token predictions out.', ['recap']),
        recap: meaning('diagram', 'The whole task', 'Text → IDs → model → next-token prediction.', ['check1', 'check2']),
        check1: meaning('question', 'What does one position predict?', 'One position predicts a distribution over the next token, using its available prefix.', ['recap']),
        answer1: meaning('annotation', 'Answer: a distribution', 'A distribution over the next token, using its available prefix.', ['check1']),
        check2: meaning('question', 'Why separate validation data?', 'Training and validation data stay separate to evaluate predictions on examples not used for the training updates.', ['recap']),
        answer2: meaning('annotation', 'Answer: held-out evaluation', 'To evaluate predictions on examples not used for the training updates.', ['check2']),
        closing: meaning('annotation', 'What comes next', 'Try the quiz, review the flashcards, or inspect text and IDs in the notebook. Lesson 2 opens the model.', []),
      },
      scene: [
        text('title', 'Text in, next-token predictions out', 40, 20, 760, 'l'),
        box('recap', 45, 100, 140, 48, 'blue'), text('recap', 'Text', 88, 113, 70, 's', 150),
        arrow('recap', 191, 124, 26, 0),
        box('recap', 223, 100, 140, 48, 'blue'), text('recap', 'IDs', 275, 113, 60, 's', 150),
        arrow('recap', 369, 124, 26, 0),
        box('recap', 401, 100, 140, 48, 'violet'), text('recap', 'model', 443, 113, 70, 's', 150),
        arrow('recap', 547, 124, 26, 0),
        box('recap', 579, 100, 190, 48, 'orange'), text('recap', 'next token', 615, 113, 120, 's', 700),
        text('check1', 'Check 1: What does one position predict?', 45, 200, 735, 'm', 3500, 'red'),
        box('answer1', 45, 245, 730, 84, 'orange', 'semi'),
        text('answer1', 'A distribution over the next token,\nfrom its prefix', 65, 259, 690, 'm', 2000, 'orange'),
        text('check2', 'Check 2: Why separate training and validation data?', 45, 360, 735, 'm', 3500, 'red'),
        box('answer2', 45, 405, 730, 56, 'orange', 'semi'),
        text('answer2', 'To evaluate on examples training never used', 65, 419, 690, 'm', 2000, 'orange'),
        text('closing', 'Finish up in Curriculum: quiz, flashcards, notebook.', 45, 490, 735, 'm', 800, 'green'),
      ],
    },
  ],
};
