# Runbook provenance stamp (packages/control-plane/src/review.js): the deployed-from
# line lands under the generated-by line, dirty adds its warning, no provenance is a
# no-op. Runs the real JS via node — no port, no mock.
import json
import os
import subprocess
from pathlib import Path

HERE = Path(os.path.dirname(os.path.abspath(__file__)))
REVIEW_JS = (HERE / ".." / ".." / ".." / ".." / "packages" / "control-plane" / "src" / "review.js").resolve()

RUNBOOK = "# counter\n\n> Generated by `small` from the code — regenerated on every deploy.\n\n## What it does\n"

SCRIPT = """
import(process.argv[2]).then((m) => {
  const { runbook, app } = JSON.parse(process.argv[1]);
  process.stdout.write(m.stampProvenance(runbook, app));
}).catch((e) => { console.error(e.message); process.exit(1); });
"""


def stamp(runbook, app):
    r = subprocess.run(
        ["node", "-e", SCRIPT, json.dumps({"runbook": runbook, "app": app}), REVIEW_JS.as_uri()],
        capture_output=True, text=True, timeout=30, encoding="utf-8",  # runbook has an em dash; Windows default is cp1252
    )
    assert r.returncode == 0, r.stderr
    return r.stdout


def test_stamp_under_generated_by_line():
    app = {"repo_url": "https://github.com/acme/tools", "repo_branch": "main", "repo_commit": "a3f8e21b" + "0" * 32, "repo_dirty": 0}
    out = stamp(RUNBOOK, app)
    lines = out.splitlines()
    assert lines[2].startswith("> Generated by")
    assert lines[3] == "> Deployed from github.com/acme/tools @ a3f8e21 (main)."
    assert "uncommitted" not in out


def test_stamp_dirty_adds_warning():
    app = {"repo_url": "https://github.com/acme/tools", "repo_branch": "main", "repo_commit": "a3f8e21b" + "0" * 32, "repo_dirty": 1}
    assert "> Deployed from github.com/acme/tools @ a3f8e21 (main). Deployed with uncommitted changes." in stamp(RUNBOOK, app)


def test_stamp_no_provenance_is_noop():
    assert stamp(RUNBOOK, {"repo_commit": None}) == RUNBOOK
    assert stamp(RUNBOOK, None) == RUNBOOK


def test_stamp_prepends_when_generated_by_line_missing():
    out = stamp("# x\n\n## What it does\n", {"repo_url": None, "repo_branch": "main", "repo_commit": "beef1234", "repo_dirty": 0})
    assert out.startswith("> Deployed from local repo @ beef123 (main).\n\n# x\n")
